### ISSUE TITLE
Won't build on Win7-64

### ISSUE THREAD

**Issue by mark-summerfield** [MoAlyousef/fltk-rs#217]
I copied the hello.rs example from the main web page. On Linux it builds and runs correctly. On Win7-64 with Rust 1.44.1 it fails as follows:
```
error: failed to run custom build command for `fltk-sys v0.7.12`

Caused by:
  process didn't exit successfully: `C:\tmp\targets\comparepdfcmd\release\build\fltk-sys-fbe273d853ade65c\build-script-build` (exit code: 101)
--- stdout
cargo:rerun-if-changed=build.rs

--- stderr
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "The system cannot find the file specified." }', C:\Users\mark\.cargo\registry\src\github.com-1ecc6299db9ec823\fltk-sys-0.7.12\build.rs:37:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

warning: build failed, waiting for other jobs to finish...
error: build failed
```
Here's the attempt with the backtrace:
```
error: failed to run custom build command for `fltk-sys v0.7.12`

Caused by:
  process didn't exit successfully: `C:\tmp\targets\hellofltk\release\build\fltk-sys-fbe273d853ade65c\build
-script-build` (exit code: 101)
--- stdout
cargo:rerun-if-changed=build.rs

--- stderr
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "The system cannot find the file specified." }', C:\Users\mark\.cargo\registry\src\github.com-1ecc6299db9ec823\fltk-sys-0.7.12\build.rs:37:9
stack backtrace:
   0: std::sys_common::backtrace::_print::{{impl}}::fmt
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\/src\libstd\sys_common\backtrace.rs:59
   1: core::fmt::write
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\/src\libcore\fmt\mod.rs:1069
   2: std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\/src\libstd\io\mod.rs:1505
   3: std::panicking::default_hook::{{closure}}
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\/src\libstd\panicking.rs:198
   4: std::panicking::default_hook
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\/src\libstd\panicking.rs:220
   5: std::panicking::rust_panic_with_hook
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\/src\libstd\panicking.rs:518
   6: std::panicking::begin_panic_handler
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\/src\libstd\panicking.rs:419
   7: core::panicking::panic_fmt
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\/src\libcore\panicking.rs:111
   8: core::option::expect_none_failed
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\/src\libcore\option.rs:1268
   9: __mb_cur_max
  10: __mb_cur_max
  11: std::rt::lang_start_internal
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\/src\libstd\rt.rs:51
  12: main
  13: __scrt_common_main_seh
             at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:253
  14: BaseThreadInitThunk
  15: RtlUserThreadStart
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by MoAlyousef** [comment]
Hi
The line the build script is failing at is Command::new("curl"). 
I suppose you’re building with the fltk-bundled flag. Normally when you install visual studio you would get curl and tar. You can try rerunning the build through the native command prompt. Normally when you type "native" at the start menu it should appear. 

The second option is to build without the fltk-bundled flag, but you’ll need to have cmake installed.

**Comment by mark-summerfield** [comment]
Thank you for your quick and helpful reply. I got rid of the bundled flag and now it works fine.
