### ISSUE TITLE
Divide by zero panic in Pack.auto_layout() [corner case] 

### ISSUE THREAD

**Issue by dheijl** [MoAlyousef/fltk-rs#534]
An empty pack will divide by zero in auto_layout:

```rust
    let mut p2c_v = Pack::new(0, 0, 640, 25, "");
    p2c_v.set_spacing(4);
    p2c_v.set_type(PackType::Vertical);
    p2c_v.auto_layout();
    p2c_v.end();
```
```
thread 'main' panicked at 'attempt to divide by zero',...\fltk-0.15.4\src\group.rs:329:17
stack backtrace:
...snip...
   3: fltk::group::Pack::auto_layout
             at C:\Users\Danny\.cargo\registry\src\github.com-1ecc6299db9ec823\fltk-0.15.4\src\group.rs:329
   4: draw::main
             at .\src\main.rs:20
   5: core::ops::function::FnOnce::call_once<fn(),tuple<>>
             at C:\Users\Danny\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\core\src\ops\function.rs:227
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

Not that anyone is likely to do this, but I encountered it when playing with Packs...

**Comment by MoAlyousef** [comment]
Hi,
Thanks for reporting it. I have added a check for 0 children in master which should appear in the next patch.

**Comment by dheijl** [comment]
Thanks!
