### ISSUE TITLE
[BUG] Panic with 1.06 in  wind.set_icon(Some(icon));

### ISSUE THREAD

**Issue by dheijl** [MoAlyousef/fltk-rs#654]
After recompiling with 1.06 
```rust
  wind.set_icon(Some(icon)); 
``` 
panics:

```
thread 'main' panicked at 'assertion failed: !(*ptr).is_null()', C:\Users\Danny\.cargo\registry\src\github.com-1ecc6299db9ec823\fltk-1.0.6\src\image.rs:207:10
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0\/library\std\src\panicking.rs:493
   1: core::panicking::panic_fmt
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0\/library\core\src\panicking.rs:92
   2: core::panicking::panic
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0\/library\core\src\panicking.rs:50
   3: fltk::image::{{impl}}::to_rgb_data
             at C:\Users\Danny\.cargo\registry\src\github.com-1ecc6299db9ec823\fltk-1.0.6\src\image.rs:207
   4: fltk::image::{{impl}}::to_rgb
             at C:\Users\Danny\.cargo\registry\src\github.com-1ecc6299db9ec823\fltk-1.0.6\src\image.rs:207
   5: fltk::window::{{impl}}::set_icon<fltk::image::SvgImage>
             at C:\Users\Danny\.cargo\registry\src\github.com-1ecc6299db9ec823\fltk-1.0.6\src\window.rs:181
   6: swyh_rs::ui::mainform::MainForm::create
             at .\src\ui\mainform.rs:77
   7: swyh_rs::main
             at .\src\main.rs:180
   8: core::ops::function::FnOnce::call_once<fn(),tuple<>>
             at C:\Users\Danny\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\core\src\ops\function.rs:227
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
error: process didn't exit successfully: `target\debug\swyh-rs.exe` (exit code: 101)

```

**Comment by MoAlyousef** [comment]
Hi
I've reverted this and will be publishing in 1.0.7. It's proving to be complex!

**Comment by dheijl** [comment]
Using 1.07 from git master is OK again, thanks!
